Create tutorial.rst
Lekaveh/MetalCoordAnalysis pull request #1
Opened 2024-09-19 20:27 UTC by Lekaveh

2024-09-19 22:55 UTC, keitaroyam requested changes
Thank you @MartinMalyMM. I think json2restraints.py should be included in this pull request.

> Further, for an particular atom considering a particular coordination, the report consists of three sections: base, angles and pdb. All the stated ideal values have also their standard deviations denoted as std.

I would suggest to show a snippet of json file here.

> For instance consider the following case: an interaction of an iron (possessing a coordination of 4) with a carbon atom is reported in a JSON file.

Can you provide a PDB code that showcases this interaction? Plus, wouldn't "-c 3" eliminate the real interactions with coordination of four in the file (if exist)? Then it does not sound a good solution.

2024-09-24 16:30 UTC, MartinMalyMM commented
I addressed the issues, added more examples and attached the relevant files and scripts.

2024-09-25 07:24 UTC, merged

2024-09-26 22:22 UTC, keitaroyam commented on tutorial/traingles.py
> +            dist_max = 1.3 * (cra1.atom.element.covalent_r + cra2.atom.element.covalent_r)
```
            dist_max = 1.3 * (cra1.atom.element.covalent_r + cra2.atom.element.covalent_r)
```
factor?

2024-09-26 22:22 UTC, keitaroyam commented on tutorial/json2restraints.py
> +                    connection.partner1.atom.element.is_metal or \
partner1/2 (gemmi.AtomAddress objects) don't have `atom` member.